### ISSUE TITLE
CPAN Pull Request Challenge ideas

### ISSUE THREAD

**Issue by bldewolf** [sparky/perl-Net-Curl#12]
Hello!  I signed up for the [2015 CPAN pull request challenge ](http://neilb.org/2014/11/29/pr-challenge-2015.html) and my first assignment is your project.  I was wondering if you had any ideas for things for me to work on, otherwise I'll start poking at TODO items.

**Comment by creaktive** [comment]
Thanks a lot, and sorry for the delay, I was on a (disconnected) vacation.
You could fix some failing tests: http://cpantesters.org/distro/N/Net-Curl.html
Most of them do fail because of the outdated `inc/symbols-in-versions` file: looks like the new release of libcurl deprecated one of the features, so Net::Curl needs to know which one.
